### ISSUE TITLE
Window icon is wrong (generic "X" icon)

### ISSUE THREAD

**Issue by geekley** [flathub/com.github.PintaProject.Pinta#19] opened 2021-11-03 21:36 UTC
In flatpak, Pinta icon in windows is wrong (it shows the generic "X" icon), and I can only fix it by using Kubuntu Window Rules and setting the "pinta" window class to the desktop file name "com.github.PintaProject.Pinta.desktop".
Something must be missing in the flatpak packaging, or in the upstream code.

The icon shows normally in the start menu and taskbar, it's only wrong in the windows (both normal and dialog windows).

---
Operating System: Kubuntu 21.04 amd64
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-38-generic
Graphics Platform: X11

**Comment by darkdragon-001** [comment] 2021-11-26 08:41
I have no idea what could be wrong. It works in Ubuntu Gnome. If you find out what is wrong, I am happy to accept a PR :wink:

**Comment by darkdragon-001** [comment] 2022-01-09 13:03
@geekley Can you reproduce this issue with the latest version? Can you reproduce it also with the non-Flatpak one?

**Comment by geekley** [comment] 2022-01-13 19:54
It happens in:
v2.0.1, flatpak
v2.0.1, snap

Doesn't happen in:
v1.6-2, apt from ubuntu impish/universe amd64

I didn't find a non-sandboxed v2.0.1 to test (I think the tar.gz and zip are just sources). I don't know if this is a bug in pinta that was fixed in apt by maintainers, or if it's a bug in both snap and flatpak packaging of pinta, or if it's a bug in pinta that appears in both because of the sandboxing.
But I can still fix it like I said above, with Window Rules.
Maybe this should be reported upstream (I can't remember if I already did that, I think I didn't).

**Comment by geekley** [comment] 2022-01-13 20:07
How weird. Now I can't reproduce it anymore ... All I did was installing/uninstalling the snap and apt versions of pinta ...
I thought it might have to do with `gnome-icon-theme` which was installed by apt but didn't uninstall when I purged pinta. But even after I purged that too, the icon is still appearing properly when I start flatpak pinta. I would try restarting (icon cache?), but I'm kinda busy now :sweat_smile: Anyways, it MIGHT be related to that.

**Comment by darkdragon-001** [comment] 2022-01-19 19:53
As you can't reproduce it any more, I am closing this issue. Please re-open in case it re-appears after reboot.

**Closed as completed by darkdragon-001** 2022-01-19 19:53 UTC

**Comment by geekley** [comment] 2022-01-21 02:14
Just checked today and it's still working for me, icon seems to be fixed now. No idea what went wrong before.
